<a href="https://colab.research.google.com/github/SangeetaChatterjee/WD_Truecue_Hackathon/blob/main/Sustainability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# IMPORTING REQUIRED PACKAGES

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
# ESTABLISHING CONNECTION AND READING FILES

from google.colab import drive
drive.mount('/content/drive')

dataset = pd.read_excel('/content/drive/My Drive/Python_Colab/TrueCue_Hackathon/Sustainability_Hackathon_Dataset.xlsx')
dataset.head(5)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

  Country Name  ... World Regions (UN SDG Definition)
0        Aruba  ...       Latin America and Caribbean
1        Aruba  ...       Latin America and Caribbean
2        Aruba  ...       Latin America and Caribbean
3        Aruba  ...       Latin America and Caribbean
4        Aruba  ...       Latin America and Caribbean

[5 rows x 54 columns]

In [16]:
dataset.shape

(3287, 54)

In [18]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3287 entries, 0 to 3286
Data columns (total 54 columns):
 #   Column                                                                                        Non-Null Count  Dtype
---  ------                                                                                        --------------  -----
 0   Country Name                                                                                  3287 non-null   object
 1   Country Code                                                                                  3287 non-null   object
 2   Year                                                                                          3287 non-null   int64
 3   Access to electricity (% of population) - EG.ELC.ACCS.ZS                                      3193 non-null   float64
 4   Adjusted net national income per capita (annual % growth) - NY.ADJ.NNTY.PC.KD.ZG              2566 non-null   float64
 5   Adjusted net savings, excluding particulate emission damage (% of GNI) - NY.ADJ.SVNX.GN.ZS    2628 non-null   float64
 6   Adjusted savings: carbon dioxide damage (% of GNI) - NY.ADJ.DCO2.GN.ZS                        3220 non-null   float64
 7   Adjusted savings: natural resources depletion (% of GNI) - NY.ADJ.DRES.GN.ZS                  3094 non-null   float64
 8   Adjusted savings: net forest depletion (% of GNI) - NY.ADJ.DFOR.GN.ZS                         3111 non-null   float64
 9   Adjusted savings: particulate emission damage (% of GNI) - NY.ADJ.DPEM.GN.ZS                  3099 non-null   float64
 10  Automated teller machines (ATMs) (per 100,000 adults) - FB.ATM.TOTL.P5                        2285 non-null   float64
 11  Broad money (% of GDP) - FM.LBL.BMNY.GD.ZS                                                    2777 non-null   float64
 12  Children out of school (% of primary school age) - SE.PRM.UNER.ZS                             2225 non-null   float64
 13  Compulsory education, duration (years) - SE.COM.DURS                                          2979 non-null   float64
 14  Cost of business start-up procedures, female (% of GNI per capita) - IC.REG.COST.PC.FE.ZS     2501 non-null   float64
 15  Cost of business start-up procedures, male (% of GNI per capita) - IC.REG.COST.PC.MA.ZS       2501 non-null   float64
 16  Exports of goods and services (% of GDP) - NE.EXP.GNFS.ZS                                     3118 non-null   float64
 17  Final consumption expenditure (% of GDP) - NE.CON.TOTL.ZS                                     3047 non-null   float64
 18  GDP (current US$) - NY.GDP.MKTP.CD                                                            3246 non-null   float64
 19  GDP per capita (current US$) - NY.GDP.PCAP.CD                                                 3246 non-null   float64
 20  General government final consumption expenditure (% of GDP) - NE.CON.GOVT.ZS                  3031 non-null   float64
 21  Gross national expenditure (% of GDP) - NE.DAB.TOTL.ZS                                        3047 non-null   float64
 22  Gross savings (% of GDP) - NY.GNS.ICTR.ZS                                                     2774 non-null   float64
 23  Imports of goods and services (% of GDP) - NE.IMP.GNFS.ZS                                     3118 non-null   float64
 24  Inflation, consumer prices (annual %) - FP.CPI.TOTL.ZG                                        3083 non-null   float64
 25  Primary completion rate, total (% of relevant age group) - SE.PRM.CMPT.ZS                     2226 non-null   float64
 26  Proportion of seats held by women in national parliaments (%) - SG.GEN.PARL.ZS                3062 non-null   float64
 27  Pupil-teacher ratio, primary - SE.PRM.ENRL.TC.ZS                                              2366 non-null   float64
 28  Renewable electricity output (% of total electricity output) - EG.ELC.RNEW.ZS                 2771 non-null   float64
 29  Renewable energy consumption (% of total final energy consumption) - EG.FEC.RNEW.ZS           3287 non-null   float64
 30  School enrollment, preprimary (% gross) - SE.PRE.ENRR                                         2349 non-null   float64
 31  School enrollment, primary (% gross) - SE.PRM.ENRR                                            2783 non-null   float64
 32  School enrollment, secondary (% gross) - SE.SEC.ENRR                                          2430 non-null   float64
 33  Trade (% of GDP) - NE.TRD.GNFS.ZS                                                             3118 non-null   float64
 34  Women Business and the Law Index Score (scale 1-100) - SG.LAW.INDX                            3211 non-null   float64
 35  Prevalence of undernourishment (%) - SN_ITK_DEFC - 2.1.1                                      1834 non-null   float64
 36  Proportion of population below international poverty line (%) - SI_POV_DAY1 - 1.1.1           1304 non-null   float64
 37  Proportion of population covered by at least a 2G mobile network (%) - IT_MOB_2GNTWK - 9.c.1  2349 non-null   float64
 38  Proportion of population covered by at least a 3G mobile network (%) - IT_MOB_3GNTWK - 9.c.1  1357 non-null   float64
 39  Proportion of population using basic drinking water services (%) - SP_ACS_BSRVH2O - 1.4.1     1837 non-null   float64
 40  Unemployment rate, male (%) - SL_TLF_UEM - 8.5.2                                              1807 non-null   float64
 41  Unemployment rate, women (%) - SL_TLF_UEM - 8.5.2                                             1806 non-null   float64
 42  Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes         3285 non-null   float64
 43  Continent                                                                                     3285 non-null   object
 44  Gini index (World Bank estimate) - SI.POV.GINI                                                1303 non-null   float64
 45  Income Classification (World Bank Definition)                                                 3285 non-null   object
 46  Individuals using the Internet (% of population) - IT.NET.USER.ZS                             2986 non-null   float64
 47  Life expectancy at birth, total (years) - SP.DYN.LE00.IN                                      3096 non-null   float64
 48  Population, total - SP.POP.TOTL                                                               3106 non-null   float64
 49  Regime Type (RoW Measure Definition)                                                          3076 non-null   object
 50  Rural population (% of total population) - SP.RUR.TOTL.ZS                                     3278 non-null   float64
 51  Total natural resources rents (% of GDP) - NY.GDP.TOTL.RT.ZS                                  3053 non-null   float64
 52  Urban population (% of total population) - SP.URB.TOTL.IN.ZS                                  3106 non-null   float64
 53  World Regions (UN SDG Definition)                                                             3285 non-null   object
dtypes: float64(47), int64(1), object(6)
memory usage: 1.4+ MB

In [13]:
dataset.nunique()

Country Name                                                                                     173
Country Code                                                                                     173
Year                                                                                              19
Access to electricity (% of population) - EG.ELC.ACCS.ZS                                        1735
Adjusted net national income per capita (annual % growth) - NY.ADJ.NNTY.PC.KD.ZG                2566
Adjusted net savings, excluding particulate emission damage (% of GNI) - NY.ADJ.SVNX.GN.ZS      2628
Adjusted savings: carbon dioxide damage (% of GNI) - NY.ADJ.DCO2.GN.ZS                          3220
Adjusted savings: natural resources depletion (% of GNI) - NY.ADJ.DRES.GN.ZS                    2809
Adjusted savings: net forest depletion (% of GNI) - NY.ADJ.DFOR.GN.ZS                           1049
Adjusted savings: particulate emission damage (% of GNI) - NY.ADJ.DPEM.GN.ZS                    2937
Automated teller machines (ATMs) (per 100,000 adults) - FB.ATM.TOTL.P5                          2274
Broad money (% of GDP) - FM.LBL.BMNY.GD.ZS                                                      2777
Children out of school (% of primary school age) - SE.PRM.UNER.ZS                               2205
Compulsory education, duration (years) - SE.COM.DURS                                              14
Cost of business start-up procedures, female (% of GNI per capita) - IC.REG.COST.PC.FE.ZS        927
Cost of business start-up procedures, male (% of GNI per capita) - IC.REG.COST.PC.MA.ZS          924
Exports of goods and services (% of GDP) - NE.EXP.GNFS.ZS                                       3118
Final consumption expenditure (% of GDP) - NE.CON.TOTL.ZS                                       3047
GDP (current US$) - NY.GDP.MKTP.CD                                                              3243
GDP per capita (current US$) - NY.GDP.PCAP.CD                                                   3246
General government final consumption expenditure (% of GDP) - NE.CON.GOVT.ZS                    3031
Gross national expenditure (% of GDP) - NE.DAB.TOTL.ZS                                          3047
Gross savings (% of GDP) - NY.GNS.ICTR.ZS                                                       2774
Imports of goods and services (% of GDP) - NE.IMP.GNFS.ZS                                       3118
Inflation, consumer prices (annual %) - FP.CPI.TOTL.ZG                                          3082
Primary completion rate, total (% of relevant age group) - SE.PRM.CMPT.ZS                       2225
Proportion of seats held by women in national parliaments (%) - SG.GEN.PARL.ZS                   903
Pupil-teacher ratio, primary - SE.PRM.ENRL.TC.ZS                                                2364
Renewable electricity output (% of total electricity output) - EG.ELC.RNEW.ZS                   2266
Renewable energy consumption (% of total final energy consumption) - EG.FEC.RNEW.ZS             3176
School enrollment, preprimary (% gross) - SE.PRE.ENRR                                           2349
School enrollment, primary (% gross) - SE.PRM.ENRR                                              2782
School enrollment, secondary (% gross) - SE.SEC.ENRR                                            2430
Trade (% of GDP) - NE.TRD.GNFS.ZS                                                               3118
Women Business and the Law Index Score (scale 1-100) - SG.LAW.INDX                               106
Prevalence of undernourishment (%) - SN_ITK_DEFC - 2.1.1                                         399
Proportion of population below international poverty line (%) - SI_POV_DAY1 - 1.1.1              285
Proportion of population covered by at least a 2G mobile network (%) - IT_MOB_2GNTWK - 9.c.1     372
Proportion of population covered by at least a 3G mobile network (%) - IT_MOB_3GNTWK - 9.c.1     403
Proportion of population using basic drinking water services (%) - SP_ACS_BSRVH2O - 1.4.1         66
Unemployment rate, male (%) - SL_TLF_UEM - 8.5.2                                                 259
Unemployment rate, women (%) - SL_TLF_UEM - 8.5.2                                                301
Annual production-based emissions of carbon dioxide (CO2), measured in million tonnes           2978
Continent                                                                                          6
Gini index (World Bank estimate) - SI.POV.GINI                                                   331
Income Classification (World Bank Definition)                                                      4
Individuals using the Internet (% of population) - IT.NET.USER.ZS                               2447
Life expectancy at birth, total (years) - SP.DYN.LE00.IN                                        2925
Population, total - SP.POP.TOTL                                                                 3105
Regime Type (RoW Measure Definition)                                                               4
Rural population (% of total population) - SP.RUR.TOTL.ZS                                       3137
Total natural resources rents (% of GDP) - NY.GDP.TOTL.RT.ZS                                    2988
Urban population (% of total population) - SP.URB.TOTL.IN.ZS                                    2974
World Regions (UN SDG Definition)                                                                  7
dtype: int64